name: rapids-benchmark
type: job
image:
  type: build
  build_spec:
    type: tfy-python-buildpack
    command: python rapids_cuDF_benchmark.py
    cuda_version: 12.0-cudnn8
    python_version: '3.11'
    requirements_path: requirements.txt
    build_context_path: .
  # `build_source.branch_name` and `build_source.ref` will automatically be patched during deployment.
  build_source:
    ref: 8f732d03f0b0e5485a3afceb7261e83d37fa0cb4
    type: git
    repo_url: https://github.com/rishiraj-tf/Rapids-benchmark
    branch_name: main
retries: 0
trigger:
  type: manual
resources:
  node:
    type: node_selector
    capacity_type: spot_fallback_on_demand
  devices:
    - name: T4
      type: nvidia_gpu
      count: 4
  cpu_limit: 16
  cpu_request: 14
  memory_limit: 64000
  memory_request: 54400
  ephemeral_storage_limit: 100000
  ephemeral_storage_request: 20000
workspace_fqn: tfy-gtl-b-us-central-1:rishi-workspace